server:
  port: 8001
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/acl_demo
    username: postgres
    password: esscsmfu2
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  mvc:
    static-pattern=/uploads/**
  resource:
    static-locations=file:/uploads/
authentication:
  secret-key: ${{ SECRET_KEY_brnwon_*&$#-good}}
  access-token:
    expiration-in-seconds: 18800
  refresh-token:
    expiration-in-seconds: 86400